version: '1.0'

services:
  python_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # 確保 postgres_db 服務啟動後，python_app 服務才啟動
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql